apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-app
  labels:
    app: agri-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agri-app
  template:
    metadata:
      labels:
        app: agri-app
    spec:
      containers:
      - name: agri-app
        image: aslq/agri-app:latest  # DockerHub profilingizga moslang
        ports:
        - containerPort: 5000
